const express = require('express')
const router = express.Router()

const passport = require('../../config/passport')
const getUsers = require('./handlers/getUsers')
const getUser = require('./handlers/getUser')
const getUserById = require('./handlers/getUserById.js')
const updateProfile = require('./handlers/updateProfile')
const addFriend = require('./handlers/addFriend')
const getFriends = require('./handlers/getFriends.js')
const getFriendsByJob = require('./handlers/getFriendsByJob')
const getFriendsJobs = require('./handlers/getFriendsJobs')
const getInboxMessages = require('./handlers/getInboxMessages')
const getOutboxMessages = require('./handlers/getOutboxMessages')
const getSuggestions = require('./handlers/getSuggestions')
const { captureParams, sendMessage, saveMessage, sendingMessagesResultOk } = require('./handlers/sendMessage')
const { captureOutboxParams, removeOutboxMessageById, removeOutboxMessageResultOk } = require('./handlers/removeOutboxMessageById')
const { captureInboxParams, removeInboxMessageById, removeInboxMessageResultOk } = require('./handlers/removeInboxMessageById')

router.use(passport.authenticate('jwt', { session: false }))

router.get('/user', getUser)
router.get('/user/:id', getUserById)
router.put('/user/:_id', addFriend)
router.get('/users', getUsers)
router.put('/account', updateProfile)
router.get('/friends', getFriends)
router.get('/friends/:job', getFriendsByJob)
router.put('/message/:id', captureParams, sendMessage, saveMessage, sendingMessagesResultOk)
router.get('/messages_inbox', getInboxMessages)
router.get('/messages_outbox', getOutboxMessages)
router.delete('/message_inbox/:id', captureInboxParams, removeInboxMessageById, removeInboxMessageResultOk)
router.delete('/message_outbox/:id', captureOutboxParams, removeOutboxMessageById, removeOutboxMessageResultOk)
router.get('/friends_jobs', getFriendsJobs)
router.get('/suggestions', getSuggestions)

module.exports = router
